#!/usr/bin/env sh

makoctl restore
makoctl list | jq -c '.data | .[] | .[]' | while read notif
do
  _jq() {
    echo $notif | jq -r "${@}"
  }
  APP_NAME=$(_jq '.["app-name"] | .data')
  APP_ICON=$(_jq '.["app-icon"] | .data')
  SUMMARY=$(_jq '.["summary"] | .data')
  BODY=$(_jq '.["body"] | .data')
  echo '
    <box halign="center" width="200" spacing="20" orientation="h" space-evenly="false" class="notif">
      <image halign="center" width="100" path="'$APP_ICON'"/>
      <box spacing="5" orientation="v" halign="center" space-evenly="true" class="content">
        <label text="'$APP_NAME'" limit-width="35"></label>
        <label text="'$SUMMARY'"></label>
        <label text="'$BODY'" visible={{if $BODY = '' then 'true' else 'false'}}></label>
      </box>
    </box> '
done
